name: Generate Client Dev
on:
  workflow_dispatch:
  
jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: sdkv2
      - name: Fetch changes
        working-directory: ./tools
        run: |
          API_BASE_URL=${{ secrets.MDB_CURRENT_API_PREVIEW_URL }} make fetch_openapi
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
        with:
          files: |
             **/atlas-api.yaml
      - name: Run generation
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        working-directory: ./tools
        run: make clean_and_generate
      - uses: peter-evans/create-pull-request@v5
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          title: "Test OpenAPI client update"
          commit-message: "openapi client update"
          delete-branch: true
          draft: true
          base: sdkv2
          branch: sdkv2dev
          body: "Alpha SDK for testing"

